const peribahasa = [
  'Ada uang ada barang',
  'Adat bersendi syarak, syarak bersendi adat',
  'Adat diisi, lembaga dituang',
  'Adat periuk berkerak, Adat lesung berdekak',
  'Adat sepanjang jalan, cupak sepanjang betung',
  'Air beriak tanda tak dalam',
  'Air besar batu bersibak',
  'Air diminum rasa duri, nasi dimakan rasa sekam',
  'Akal tak sekali tiba',
  'Akik disangka batu',
  'Akal pulas tak patah',
  'Alur bertempuh, jalan berturut',
  'Ampang sampai ke seberang, dinding sampai ke langit',
  'Amra disangka kedondong',
  'Anak dipangku dilepaskan, beruk di rimba disusukan',
  'Anak orang, anak orang juga',
  'Angan lalu paham bertumbuk',
  'Angan-angan menerawang langit',
  'Angan mengikut tubuh',
  'Angguk bukan, geleng ia',
  'Bagai anak ayam kehilangan induk',
  'Berdiang di abu dingin',
  'Berkepanjangan bagai agam',
  'Berguru kepalang ajar, bagai bunga kembang tak jadi',
  'Berbilang dari esa, mengaji dari alif',
  'Bagai alu pencungkil duri',
  'Bagai dientak alu luncung',
  'Bagai guna-guna alu sesudah menumbuk dicampakkan',
  'Belum beranak sudah ditimang',
  'Babi merasa gulai',
  'Badak makan anak',
  'Besar kayu besar bahannya, kecil kayu kecil bahannya',
  'Bahasa menunjukkan bangsa',
  'Berjalan sampai ke batas, berlayar sampai ke pulau',
  'Batu hitam tak bersanding',
  'Bagai pinang dibelah dua',
  'Buruk muka cermin dibelah',
  'Cacing hendak menjadi naga',
  'Condong yg akan menimpa',
  'Coreng arang di muka',
  'Cencaru makan petang',
  'Cencang dua segeragai',
  'Cencang putus tiang tumbuk',
  'Cekur jerangau, ada lagi di umbun-umbun',
  'Ditimbun anai-anai',
  'Di alas bagai memengat',
  'Dalam laut boleh ajuk, dalam hati siapa tahu',
  'Dangkal telah keseberangan, dalam telah ajuk',
  'Dari semak ke belukar',
  'Empang sampai ke seberang, dinding sampai ke langit',
  'Enau mencari',
  'Endap di balik lalang sehelai',
  'Enggan seribu daya, mau sepatah kata',
  'Esa hilang dua terbilang',
  'Gila di abun – abun',
  'Gajah mati meninggalkan gading, orang mati meninggalkan nama',
  'Galas terdorong kepada Cina',
  'Gamak-gamak seperti menyambal',
  'Gayung bersambut, kata berjawab',
  'Gelegar buluh',
  'Geleng spt si patung kenyang',
  'Gemuk membuang lemak, cerdik membuang kawan',
  'Gengam erat membuhul mati',
  'Habis beralur maka beralu-alu',
  'Habis pati ampas dibuang',
  'Hancur badan dikandung tanah, budi baik terkenang jua',
  'Hakim kepada beruk',
  'Hangat-hangat tahi ayam',
  'Harimau mati karena belangnya',
  'Hemat pangkal kaya, rajin pangkal pandai',
  'Hidung dicium pipi digigit',
  'Hitam di atas putih',
  'Ingat sebelum kena, ingat sebelum habis',
  'Ijuk tak bersagar',
  'Ikan di laut, asam di gunung, bertemu dalam belanga',
  'Ikut hati mati, ikut mata buta',
  'Ilmu padi, makin berisi makin runduk',
  'Indah kabar dari rupa',
  'Isi lemak dapat ke orang, tulang bulu pulang ke kita',
  'Jadi abu arang',
  'Jadi alas cakap',
  'Jika pisau tiada baja, makin dikikir bertambah tumpul',
  'Kalah jadi abu, menang jadi arang',
  'Kalah limau oleh benalu',
  'Kalah sabung menang sorak',
  'Karena nila setitik, rusak susu sebelanga',
  'Kain lama dicampak buang, kain baru pula di cari',
  'Kaki naik kepala turun',
  'Kapal satu nakhoda dua',
  'Kasihan anak tangan-tangankan, kasihan biji tinggal-tinggalkan',
  'Kecil-kecil anak kalau sudah besar onak',
  'Ladang yg berpunya',
  'Laki pulang kelaparan, dagang lalu ditanakkan',
  'Langkas buah pepaya',
  'Laut mana yang tak berombak, bumi mana yang tak ditimpa hujan',
  'Layar menimpa tiang',
  'Mengairi sawah orang',
  'Mengalang-alang leher, minta disembelih',
  'Membeli menang memakai kalah',
  'Memikul di bahu, menjunjung di kepala',
  'Tangan mencencang',
  'Mencabik baju di dada',
  'Menegakkan benang basah',
  'Menggantang anak ayam',
  'Orang mengantuk disorongkan bantal ',
  'Ombak yang kecil jangan diabaikan',
  'Orang yang kaya juga yang bertambah kekayaannya anak baik menantu molek',
  'Pelanduk di dalam cerang rimba',
  'Pecah anak buyung, tempayan ada',
  'Rusak bangsa oleh laku',
  'Rusak anak oleh menantu',
  'Seperti abu di atas tanggul',
  'Sungguhpun kawat yang dibentuk, ikan di laut yang diadang',
  'Sebelum ajal berpantangan mati',
  'Subur karena dipupuk, besar karena ambak',
  'Sedangkan bah kapal tak hanyut, ini pula kemarau panjang',
  'Seperti cacing kepanasan',
  'Setinggi-tinggi bangau terbang, surutnya ke kubangan',
  'Sepala-pala mandi biarlah basah',
  'Segenggam digunungkan, setitik dilautkan',
  'Selama hayat dikandung badan',
  'Terpegang di abu hangat',
  'Tercincang puar bergerak andilau',
  'Terajar pd banteng pincang',
  'Terpijak bara hangat',
  'Tak ada gading yang tak retak',
  'Usul menunjukkan asal, ',
  'Utang emas boleh dibayar, Utang budi dibawa mati',
  'Utang tiap helai bulu',
  'Zaman beralih musim bertukar',
]
export default peribahasa